include: ../../analysis_options.yaml

analyzer:
  plugins:
    - custom_lint
  errors:
    invalid_annotation_target: ignore
    diagnostic_describe_all_properties: ignore
    lines_longer_than_80_chars: ignore
    do_not_use_environment: ignore
  exclude:
    - lib/gen/i18n/strings.g.dart
